import { useContext, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { AuthContext } from "../context/AuthContext";
export const AuthCard = ({ title, subtitle, children }) => <main className="min-h-[calc(100vh-88px)] bg-gray-950 px-4 py-12"><section className="mx-auto w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl sm:p-8"><p className="mb-2 text-sm font-bold tracking-[.2em] text-gray-500">EVENTORA</p><h1 className="text-2xl font-extrabold text-gray-950">{title}</h1><p className="mt-3 text-sm leading-6 text-gray-600">{subtitle}</p><div className="mt-8">{children}</div></section></main>;
export const Field = ({ label, type, value, onChange, autoComplete }) => <label className="block text-sm font-semibold text-gray-800">{label}<input required type={type} value={value} onChange={(event) => onChange(event.target.value)} autoComplete={autoComplete} className="mt-2 w-full rounded-xl border border-gray-300 px-4 py-3 text-gray-950 outline-none focus:border-gray-950 focus:ring-2 focus:ring-gray-200" /></label>;
const Register = () => { const { register } = useContext(AuthContext); const navigate = useNavigate(); const [form, setForm] = useState({ name: "", email: "", password: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
 const submit = async (event) => { event.preventDefault(); if (!form.name.trim() || !form.email.trim() || !form.password) return setError("Please fill in your name, email, and password."); setError(""); setLoading(true); try { const data = await register(form.name.trim(), form.email.trim(), form.password); sessionStorage.setItem("otpEmail", data.email || form.email.trim()); navigate("/verify-otp"); } catch (err) { setError(err.response?.data?.message || "Unable to create your account. Please try again."); } finally { setLoading(false); } };
 return <AuthCard title="Create your Eventora account" subtitle="Sign up to discover and book unforgettable experiences."><form onSubmit={submit} className="space-y-5"><Field label="Name" type="text" value={form.name} onChange={(name) => setForm({ ...form, name })} autoComplete="name" /><Field label="Email" type="email" value={form.email} onChange={(email) => setForm({ ...form, email })} autoComplete="email" /><Field label="Password" type="password" value={form.password} onChange={(password) => setForm({ ...form, password })} autoComplete="new-password" />{error && <p role="alert" className="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-xl bg-gray-950 px-4 py-3 font-semibold text-white hover:bg-gray-700 disabled:cursor-not-allowed disabled:opacity-60">{loading ? "Creating account..." : "Sign Up"}</button></form><p className="mt-6 text-center text-sm text-gray-600">Already have an account? <Link to="/login" className="font-semibold text-gray-950 hover:underline">Login</Link></p></AuthCard>; };
export default Register;
